# Generated by Django 6.1.1 on 2026-09-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_view_users", "Может просматривать пользователей"),
                    ("can_block_users", "Может блокировать пользователей"),
                ]
            },
        ),
    ]
