# Generated by Django 6.1.1 on 2026-09-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_message_user_messenger_user_recipient_user_attempt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attempt",
            old_name="delivery_time",
            new_name="attempt_time",
        ),
        migrations.RemoveField(
            model_name="attempt",
            name="message",
        ),
        migrations.AddField(
            model_name="attempt",
            name="mailing",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="mailing.messenger"),
        ),
        migrations.AlterField(
            model_name="messenger",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("launched", "Запущена"), ("finished", "Завершена")],
                default="created",
                max_length=8,
            ),
        ),
    ]
