# Generated by Django 6.1.1 on 2026-09-29 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_rename_delivery_time_attempt_attempt_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="recipient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="mailing.recipient"
            ),
        ),
    ]
