# Generated by Django 6.1.1 on 2026-09-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_attempt_recipient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messenger",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
    ]
