# Generated by Django 6.1.1 on 2026-09-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_messenger_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messenger",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_disable_mailings", "Может отключать рассылки"),
                    ("can_view_all_recipients", "Может просматривать всех клиентов"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
